# Generated by Django 5.1.4 on 2025-04-06 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="team",
        ),
        migrations.CreateModel(
            name="AthleticsScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Qualified", "Qualified"),
                            ("Disqualified", "Disqualified"),
                            ("Did Not Finish", "Did Not Finish"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("time", models.DurationField(blank=True, null=True)),
                (
                    "distance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("position", models.IntegerField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.event"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.match"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athletics_scores",
                        to="portal.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BadmintonScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sets_won", models.IntegerField(default=0)),
                ("points", models.IntegerField(default=0)),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[("win", "Win"), ("loss", "Loss")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.event"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.match"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badminton_scores",
                        to="portal.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CricketScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField()),
                ("overs", models.IntegerField()),
                ("wickets", models.IntegerField()),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("win", "Win"),
                            ("loss", "Loss"),
                            ("tie", "Tie"),
                            ("no_result", "No Result"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.event"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.match"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team1_score",
                        to="portal.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FootballScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goals", models.IntegerField(default=0)),
                (
                    "verdict",
                    models.CharField(
                        blank=True,
                        choices=[("win", "Win"), ("loss", "Loss"), ("draw", "Draw")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.event"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.match"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="football_scores",
                        to="portal.team",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Registration",
        ),
        migrations.DeleteModel(
            name="Score",
        ),
    ]
