# Generated by Django 5.1.6 on 2025-04-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketscore',
            name='verdict_for_team1',
            field=models.CharField(choices=[('Win', 'Win'), ('Loss', 'Loss'), ('Tie', 'Tie'), ('No Result', 'No Result')], max_length=20),
        ),
    ]
