# Generated by Django 5.1.4 on 2025-04-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_remove_score_team_athleticsscore_badmintonscore_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="event",
        ),
        migrations.AlterField(
            model_name="athleticsscore",
            name="verdict",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Qualified", "Qualified"),
                    ("Disqualified", "Disqualified"),
                    ("Did Not Finish", "Did Not Finish"),
                ],
                default="Did Not Finish",
                max_length=20,
                null=True,
            ),
        ),
    ]
