# Generated by Django 5.1.4 on 2025-04-06 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_remove_match_event_alter_athleticsscore_verdict"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="event",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="portal.event",
            ),
            preserve_default=False,
        ),
    ]
