# Generated by Django 5.1.4 on 2025-04-11 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athleticsscore",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portal.participant"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_event",
                to="portal.event",
            ),
        ),
        migrations.CreateModel(
            name="SingleScoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.event"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.match"
                    ),
                ),
                (
                    "scores",
                    models.ManyToManyField(
                        through="portal.AthleticsScore", to="portal.participant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="athleticsscore",
            name="scoring",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="portal.singlescoring",
            ),
            preserve_default=False,
        ),
    ]
