# Generated by Django 5.1.6 on 2025-03-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_event_organizer_participant_team_match_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
