# Generated by Django 5.1.4 on 2025-04-11 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_athleticsscore_participant_alter_team_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="athleticsscore",
            name="event",
        ),
        migrations.RemoveField(
            model_name="athleticsscore",
            name="match",
        ),
    ]
