# Generated by Django 5.1.4 on 2025-03-27 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_team_max_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.participant')),
            ],
        ),
    ]
