# Generated by Django 5.1.6 on 2025-04-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_singlescoringforathletics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/feedback_images/'),
        ),
    ]
